---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r load packages, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
data("ToothGrowth")
```

##Executive Summary
Here, we examine the effect of vitamin supplementation on tooth growth in guinea pigs. Vitamin C increased odontoblast length in a dose-dependent fashion. Orange juice was a more effective source of Vitamin C at lower doses, but at the highest dose there was no difference between orange juice vs ascorbic acid.


```{r quick look at the data}
str(ToothGrowth)
```

```{r summary}
summary(ToothGrowth)
```

```{r unique doses}
unique(ToothGrowth$dose)
```


```{r plot data}
ggplot(data = ToothGrowth, mapping = aes(x = dose, y = len, color = supp)) + 
    scale_x_log10() +
    scale_colour_brewer(palette = "Set1") +
    geom_point() + 
    geom_smooth(method = "lm") +
    labs(title = "Effect of vitamin C supplementation on tooth growth in guinea pigs", x = "log Dose (mg/day)", y = "Odontoblast Length (microns)") + 
    theme(plot.title = element_text(hjust = 0.5))
```

```{r}
tooth_fit <- lm(len ~ log(dose)*supp, data = ToothGrowth)
tooth_fit
```

```{r}
anova(tooth_fit)
```

