---
title: "Statistical Inference Final Project"
author: "Steven Vasquez-Grinnell"
date: "May 3, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
```


```{r mean converging}
set.seed(122)
overall_means <- data.frame(index = 1:21, overall_mean = 1:21)
all_the_means <- vector("list", length = 21)

for (i in 1:21){
  step <- 10^((i-1)/4)
  tmp_means <- vector(length = step)
  
  for (j in 1:step) {
    tmp_means[j] <- mean(rexp(40,0.2))
  }
  
  all_the_means[[i]]<-tmp_means
  
  overall_means$index[i] <- step
  overall_means$overall_mean[i] <- mean(tmp_means)
}
```

```{r q1 means converge}
ggplot(overall_means, mapping = aes(x = index, y = overall_mean, color = "red")) + 
  scale_x_log10() + 
  geom_hline(yintercept = 5) + 
  geom_point() + 
  geom_line() + 
  labs(title = "Sample Means of 40 Exponentials", x = "# of averages", y = "Mean") +
  guides(color = "none")

```

```{r q2 means approx normal}


means_df_list<- vector("list", length = 5)
  for(i in 1:5) {
    means_df_list[[i]] <- data.frame(row = 1:length(all_the_means[[i*4]]), means = all_the_means[[i*4]], cond = i)
  }
  
means_count <- lapply(all_the_means,length)
theoretical <- lapply(means_count, rnorm, mean = 5, sd = 5)

ggplot(means_df_list[[5]], mapping = aes(x = means, fill = cond)) +
  coord_cartesian(xlim = c(2,8)) +
  geom_density(alpha = 0.3) + 
  geom_vline(aes(xintercept = 5)) +
  stat_function(fun = dnorm, color = "red", args = list(mean = 5, sd = 5/sqrt(40))) +
  guides(fill = "none")

```


```{r q-q plot}
ggplot(means_df_list[[5]], mapping = aes(sample = means)) +
  coord_cartesian(ylim = c(1,10), xlim = c(-5.5,5.5)) +
  geom_qq() +
  geom_abline(intercept = mean(theoretical[[21]]), slope = sd(theoretical[[21]])/sqrt(40))

```

